In [1]:
arr = [1,2,3]
print(arr*5)
arr = [x*5 for x in arr]
print(arr)




[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]
[5, 10, 15]


In [2]:
import numpy as np 
arr1 = np.array([1,2,3])

arr1 = arr1*5
print(arr1)


[ 5 10 15]


# Ndarray

In [10]:
import numpy as np

# 1d array

arr1 = np.array([1,2,3,4,5])

print(type(arr1))

print(arr1.ndim)

# 2d array
arr2 = np.array([[1,2,3], # row 1
                 [1,2,3] # row 2
                ])

print(arr2.ndim)



#3d array
arr3 = np.array([
    # 1st floor
    [
        [1,2,3], # row1
        [4,5,6]  # row3
    ],
    #2nd floor
    [
        [1,2,3], # row1
        [4,5,6]  # row2
    ],
    # 3rd floor
    [
        [1,2,3], # row1
        [4,5,6]  # row2
    ]
])

print(arr3.ndim)


<class 'numpy.ndarray'>
1
2
3


In [12]:
# Array Attributes

# dimanension

print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)


# shape 
print(arr1.shape)
print(arr2.shape)
print(arr3.shape)


# data type
print(arr1.dtype)
print(arr2.dtype)
print(arr3.dtype)

# size
print(arr1.size)
print(arr2.size)
print(arr3.size)


1
2
3
(5,)
(2, 3)
(3, 2, 3)
int64
int64
int64
5
6
18


In [19]:
# ndarrayy data type

arr = np.array([1,2,3])

print(arr.dtype)

arr = np.array([1.5,2.4,3.2])
print(arr.dtype)

arr  = np.array([1,2,3.2])

# Upcasted to floot

print(arr.dtype)

# Upcasted to string
arr  = np.array([1,2,3,'st'])
print(arr.dtype)



int64
float64
float64
<U21


In [37]:
# Selecting a datatype of an array
arr = np.array([1,2,300])

print(arr.dtype)

arr = arr.astype(np.int32)
print(arr.dtype)

#error
# arr  = np.array([1,2,3,'st'],dtype=np.float64)
print(arr.dtype)




arr  = np.array([1,2,3,True,3.25,'st'])
print(arr.dtype)




int64
int32
int32
<U32


In [46]:
# ndarray creating from existing data

# List

lst = [12,30,430,40,34.5]
arr = np.array(lst,dtype=np.int32)
print(arr)
print(type(arr))
print(arr.dtype)



# mixed_lst = [12,True,'hello',2.34,[3,4,5]]

# arr = np.array(mixed_lst)
# print(arr)
# print(type(arr))
# print(arr.dtype)

# matrix
matrix =  [
        [1,2,3], # row1
        [4,5,6]  # row2
    ]

arr = np.array(matrix)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)



[ 12  30 430  40  34]
<class 'numpy.ndarray'>
int32
[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
int64
(2, 3)
2


In [54]:
# tuple

tpl = (19,39,49)

arr = np.array(tpl,dtype=np.int32)

print(arr.dtype)
arr = arr.astype(np.int16)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)


int32
[19 39 49]
<class 'numpy.ndarray'>
int16
(3,)
1


In [56]:

st = {1,2,3,4}
arr = np.array(list(st))
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)

[1 2 3 4]
<class 'numpy.ndarray'>
int64
(4,)
1


In [65]:
# dictionary
dc = {'a':3,'b':10,'c':20,'d':20}
keys = dc.keys()
values = dc.values()
items = dc.items()

print(keys,values,items)


arr = np.array(list(keys))
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)


print("<-------- Values to ndarray----------->")
arr = np.array(list(values))
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

print("<-------- Items to ndarray----------->")
arr = np.array(list(items))
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)



dict_keys(['a', 'b', 'c', 'd']) dict_values([3, 10, 20, 20]) dict_items([('a', 3), ('b', 10), ('c', 20), ('d', 20)])
['a' 'b' 'c' 'd']
<class 'numpy.ndarray'>
<U1
(4,)
1
4
<-------- Values to ndarray----------->
[ 3 10 20 20]
<class 'numpy.ndarray'>
int64
(4,)
1
4
<-------- Items to ndarray----------->
[['a' '3']
 ['b' '10']
 ['c' '20']
 ['d' '20']]
<class 'numpy.ndarray'>
<U21
(4, 2)
2
8


In [73]:
# Creating ndarray from scratch

# np.zeros
arr =  np.zeros((2,3),dtype=np.int8) # arr3 shape same

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)
arr =  np.zeros_like(arr3)
print(arr)
print(arr.shape)

[[0 0 0]
 [0 0 0]]
<class 'numpy.ndarray'>
int8
(2, 3)
2
6
[[[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]]
(3, 2, 3)


In [82]:
# Creating ndarray from scratch

# np.ones
arr =  np.ones((3,4,3),dtype=np.int8) # arr3 shape same

# print(arr)
# print(type(arr))
# print(arr.dtype)
# print(arr.shape)
# print(arr.ndim)
# print(arr.size)
arr =  np.ones_like(arr3)
print(arr)
print(arr.shape)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]
(3, 2, 3)


In [89]:
# empty
# Creating ndarray from scratch

# np.ones
arr =  np.empty((4,3),dtype=np.int8) # arr3 shape same

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)
arr =  np.empty_like(arr3)
print(arr)
print(arr.shape)

[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]
<class 'numpy.ndarray'>
int8
(4, 3)
2
12
[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]
(3, 2, 3)


In [107]:
# full

# empty
# Creating ndarray from scratch

# np.ones
arr =  np.full((4,3),np.inf) # arr3 shape same

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)
arr =  np.full_like(arr3,np.inf,dtype=np.float64)
print(arr)
print(arr.shape)

[[inf inf inf]
 [inf inf inf]
 [inf inf inf]
 [inf inf inf]]
<class 'numpy.ndarray'>
float64
(4, 3)
2
12
[[[inf inf inf]
  [inf inf inf]]

 [[inf inf inf]
  [inf inf inf]]

 [[inf inf inf]
  [inf inf inf]]]
(3, 2, 3)


In [111]:
# Array creation with random values

arr =  np.random.rand(2,3) # 0 - > 1 
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)


[[0.43261843 0.58997426 0.88560604]
 [0.24690336 0.81799039 0.36151965]]
<class 'numpy.ndarray'>
float64
(2, 3)
2
6


In [117]:
# Random int
# Array creation with random values

#np.random.randint(start,end,(shape,shape))

arr =  np.random.randint(1,10,(2,3)) 
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)


[[3 6 9]
 [7 8 5]]
<class 'numpy.ndarray'>
int64
(2, 3)
2
6


In [118]:
# Random int
# Array creation with random values

#np.random.uniform(start,end,(shape,shape))

arr =  np.random.uniform(1,10,(2,3)) 
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)


[[2.75677039 2.20048439 4.84117056]
 [7.37232499 3.56470184 7.4114049 ]]
<class 'numpy.ndarray'>
float64
(2, 3)
2
6


In [121]:
# Array creation with range functions
# np.arange(first,end,step) -> semilar to range function


arr = np.arange(1,10,1)
mat = arr.reshape(3,3)
print(mat)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
int64
(9,)
1
9


In [128]:
# np.linspace(start,end(included),koita)

arr = np.linspace(1,10,15)

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[ 1.          1.64285714  2.28571429  2.92857143  3.57142857  4.21428571
  4.85714286  5.5         6.14285714  6.78571429  7.42857143  8.07142857
  8.71428571  9.35714286 10.        ]
<class 'numpy.ndarray'>
float64
(15,)
1
15


In [132]:
# np.logspace(start,end(included),koita)
arr = np.logspace(0,4,5,base=2)

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[ 1.  2.  4.  8. 16.]
<class 'numpy.ndarray'>
float64
(5,)
1
5


In [135]:
# creating matrix for linear algebra

diagonal_matrix = np.diag([1,2,3])
print(diagonal_matrix)
print(diagonal_matrix.shape)


[[1 0 0]
 [0 2 0]
 [0 0 3]]
(3, 3)


In [144]:
# Identity matrix
# identity_mat = np.eye(3)
# print(identity_mat)
# print(identity_mat.shape)


# np.eye(row,column)
mat = np.eye(3,4)
print(mat)
print("---")
mat = np.eye(3,4,1)
print(mat)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]
---
[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [158]:
# Indexing and slicing

print(arr1)
# print(arr2)
# print(arr1[2])
# arr1[2] = 100
# print(arr1[2])
# print(arr1)
print(arr2)
arr2[0][2] = 2300
print(arr2)
print(arr2[0][2])

[  1   2 100   4   5]
[[   1    2 2300]
 [   1    2    3]]
[[   1    2 2300]
 [   1    2    3]]
2300


In [187]:
# slicing
# 1d = arr[start:end:step]
arr1_mod = arr1[1:4].copy()
print(arr1_mod)
arr1_mod[0] = 500
print(arr1_mod)
print(arr1)

#2d slicing 
# arr[row_start:row_end:step,column_start:column_end:step]

# print(arr2)

# getting ar row
row_0 = arr2[0:1,]
row_1 = arr2[1:,]
# print(row_0)
# print(row_1)


# getting a column
# col_0 = arr2[::,0:1]
# col_1 = arr2[::,1:2]
# print(col_0)
# print(col_1)



# getting a portion
portion = arr2[::,0:2]
# print(portion)

[400 100   4]
[500 100   4]
[  1 400 100   4   5]


In [198]:
# Advance indexing
lst = np.array([1,3,4,788,44])
values = lst[[2,3]]
# print(values)


print(arr2)
print(arr2[[0,1],[1,2]])

# using condition 
print(arr2[arr2>2])
arr2[arr2>2] = 0
print(arr2)

[[1 2 0]
 [1 2 0]]
[2 0]
[]
[[1 2 0]
 [1 2 0]]


In [203]:
arr = np.array([[12,3,4],[34,676,23]])
# for i in arr:
#     for j in i:
#         print(j)
for i in np.nditer(arr):
    print(i)

12
3
4
34
676
23


In [217]:
# print(np.linspace(0,10,5))
# n = np.full(2,2),np.inf
# print(n)

# arr = np.array([[10,20,30],[40,50,60]])
# print(arr[:,1])

# arr = np.random.rand(2,3) 
# print(arr)


arr = np.array([1,2,3,4,5])
arr[1:4] = 0
print(arr)

[1 0 0 0 5]


In [237]:
# 1. You have a list of temperatures recorded in Celsius. Your task is to:
# Create a NumPy array from the given list.
# Convert all temperatures from Celsius to Fahrenheit. The formula is F = C* 1.8 + 32.
# Print the new Fahrenheit array.

# 2.  You have a Python list containing the lap times (in seconds) for an athlete.

# Task:

# Convert the list into a NumPy array.
# Print the array's shape, size, and data type.
# The athlete wants to see their times in minutes. Create a new array by dividing all the lap times by 60.
# Print the new array of lap times in minutes.



# 1. 
temperatures_celsius = [23.5, 25.0, 19.8, 30.2, 28.4, 21.7, 26.3, 24.5, 22.0, 29.1]
numpy_array = np.array(temperatures_celsius)
# print(numpy_array)
temperatures_fahrenheit = numpy_array*1.8+32
print(f"temperatures_fahrenheit: {temperatures_fahrenheit}")



# 2.
lap_times = [72.5, 74.2, 70.8, 71.6, 73.0]
lap_numpy = np.array(lap_times)
print(f"Shape : {lap_numpy.shape}")
print(f"Size : {lap_numpy.size}")
print(f"DataType : {lap_numpy.dtype}")
lap_in_minutes = lap_numpy/60
print(f"Lap times in minutes : {[str(round(time,3))+"s" for time in lap_in_minutes]}")

temperatures_fahrenheit: [74.3  77.   67.64 86.36 83.12 71.06 79.34 76.1  71.6  84.38]
Shape : (5,)
Size : 5
DataType : float64
Lap times in minutes : ['1.208s', '1.237s', '1.18s', '1.193s', '1.217s']
