In [5]:
#1 . Create a 1D, 2D, and 3D NumPy array and print their dimensions and shapes.
import numpy as np
oneD = np.array([1, 2, 3, 4, 5])
twoD = np.array([[1, 2, 3], [4, 5, 6]])
threeD = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print({"1D":{
    "Dimenssion":oneD.ndim,
    "Shape":oneD.shape
}})

print({"2D":{
    "Dimenssion":twoD.ndim,
    "Shape":twoD.shape
}})

print({"3D":{
    "Dimenssion":threeD.ndim,
    "Shape":threeD.shape
}})


{'1D': {'Dimenssion': 1, 'Shape': (5,)}}
{'2D': {'Dimenssion': 2, 'Shape': (2, 3)}}
{'3D': {'Dimenssion': 3, 'Shape': (2, 2, 3)}}


In [19]:
# 2 . Create:
# an array of zeros of shape (3,3)


# an array of ones of shape (2,5)


# an array filled with 7

import numpy as np
Zero = np.zeros((3,3))
Ones = np.ones((2,5))
Filled = np.full((1,3),7)

print({"Zero":Zero})
print({"Ones":Ones})
print({"Filled":Filled})



{'Zero': array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])}
{'Ones': array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])}
{'Filled': array([[7, 7, 7]])}


In [31]:
# 3 . Create an array of even numbers between 10 and 50 using arange.
import numpy as np
arr = np.arange(10,50)
even = arr[arr % 2 == 0]
print({"even": even.tolist()})

{'even': [10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48]}


In [45]:
# 4 . Create a 4×4 matrix from 0–15. Then , extract:
# the first row


# the last column


# a 2×2 subarray from the center


import numpy as np
arr = np.arange(0,16)
mat_4_4 = arr.reshape(4,4)
print(mat_4_4)
first_row = mat_4_4[:1:,]
last_column = mat_4_4[::,3:]
print({"first_row":first_row})
print({"last_column":last_column})
sub_arr = mat_4_4[1:3,1:3]
print({"sub_arr":sub_arr})


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
{'first_row': array([[0, 1, 2, 3]])}
{'last_column': array([[ 3],
       [ 7],
       [11],
       [15]])}
{'sub_arr': array([[ 5,  6],
       [ 9, 10]])}


In [47]:
# 5 . Add a 1D array [1,2,3] to each row of a 3×3 matrix.
import numpy as np

arr = np.array([1,2,3])
oneD = arr.reshape(1,3)

threeD = np.array([
    [11,22,33],
    [33,44,55],
    [55,66,77]
])

new_arr = np.append(threeD,oneD,axis=0)
print(new_arr)

[[11 22 33]
 [33 44 55]
 [55 66 77]
 [ 1  2  3]]


In [51]:
# 6 . Given two arrays A and B, compute:
# (A + B) / 2


# A**2 + B**2
import numpy as np
A = np.array([11,22,33])
B = np.array([33,44,55])
SummationAndDivide = (A+B)/2
SquareAndSummation = (A**2) + (B**2)
print({"SummationAndDevide":SummationAndDivide.tolist()})
print({"SquareAndSummation":SquareAndSummation.tolist()})

{'SummationAndDevide': [22.0, 33.0, 44.0]}
{'SquareAndSummation': [1210, 2420, 4114]}
