In [4]:
import numpy as np

arr = np.random.randint(1,100,size=(10,5)) # sample - 10, feature - 5
arr.shape
# print(arr)

(10, 5)

In [13]:
b = arr.reshape(5,10)
b.shape
b.ndim
b

array([[59, 75, 89, 72,  8, 38, 95, 78, 61, 83],
       [42,  8,  5,  5, 13, 18, 35, 50, 67, 19],
       [46, 71, 95, 38, 43, 23, 45, 91, 89,  3],
       [51, 22, 20, 60, 75, 25, 56, 41, 15, 95],
       [34,  3, 79, 42, 54, 70, 60, 34, 67, 91]])

In [18]:
# flatten = b.flatten()
# print(flatten)
# b

# cloumn_wise_flattening 
# column_wise_flattening = np.ravel(b,order="F")
column_wise_flattening = np.ravel(b,order="C")
print(column_wise_flattening)


[59 75 89 72  8 38 95 78 61 83 42  8  5  5 13 18 35 50 67 19 46 71 95 38
 43 23 45 91 89  3 51 22 20 60 75 25 56 41 15 95 34  3 79 42 54 70 60 34
 67 91]


In [23]:
a = np.random.randint(1,10,size=(2,3)) # sample - 2, feature - 3
b = np.random.randint(20,30,size=(2,3)) # sample - 2, feature - 3
print(a)
print(b)

[[4 9 2]
 [7 4 5]]
[[28 25 23]
 [25 25 23]]


In [26]:
### Concatenet
con_row = np.concatenate((a,b),axis=0) # row wise
print(con_row)

con_col = np.concatenate((a,b),axis=1) # column wise
print(con_col)


[[ 4  9  2]
 [ 7  4  5]
 [28 25 23]
 [25 25 23]]
[[ 4  9  2 28 25 23]
 [ 7  4  5 25 25 23]]


In [32]:
# error

# row wise concaanate korar somoy column same thakbe 
# column wise concaanate korar somoy row same thakbe 
x = np.random.randint(1,10,size=(2,3))
print(x)

y = np.random.randint(1,10,size=(1,3)) 
print(y)
print("---")
r = np.concatenate((x,y),axis=1)
print(r)

[[8 1 2]
 [7 4 3]]
[[5 6 1]]
---


ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

In [100]:
# transpose
mat = np.array([
    [30,2,40],
    [4,20,50],
])
transpose = mat.T
print(transpose)

[[30  4]
 [ 2 20]
 [40 50]]


In [45]:
# Array split
a = np.random.randint(1,10,size=(10,)) 
print(a)


splited_array = np.array_split(a,3)
print(splited_array)


# split -> equal division
splited_array = np.split(a,3)


[7 3 2 6 1 7 8 7 3 7]
[array([7, 3, 2, 6]), array([1, 7, 8]), array([7, 3, 7])]


ValueError: array split does not result in an equal division

In [61]:
# arithmetic operator and mathematical functions
# faster for vectorization
x = np.array([10,8,30,40])
y = np.array([2,3,4,5])
add = x+y
print(add)
sub = x-y
print(sub)
mul = x*y
print(mul)
div = x/y
print(div)
reminder = x%y
print(reminder)


[12 11 34 45]
[ 8  5 26 35]
[ 20  24 120 200]
[5.         2.66666667 7.5        8.        ]
[0 2 2 0]


In [62]:
# mathematical function
# tgrigonometry
# sin,cos,tan takes values in radian
sin_val = np.sin(x)
print(sin_val)
cos_val = np.cos(x)
print(cos_val)
deg_con = np.rad2deg(x)
print(deg_con)

# degtorad

[-0.54402111  0.98935825 -0.98803162  0.74511316]
[-0.83907153 -0.14550003  0.15425145 -0.66693806]
[ 572.95779513  458.3662361  1718.87338539 2291.83118052]


In [66]:
# log
x = np.array([10,8,16,40])

base_10_log_val = np.log10(x)
print(base_10_log_val)

two_diye_bhag = np.log2(x)
print(two_diye_bhag)



sqrt = np.sqrt(x)
print(sqrt)



[1.         0.90308999 1.20411998 1.60205999]
[3.32192809 3.         4.         5.32192809]
[3.16227766 2.82842712 4.         6.32455532]


In [71]:
# different
s = np.sum(x)
print(s)

#  prefix sum
cumul =  np.cumulative_sum(x)
print(cumul)


74
[10 18 34 74]


In [76]:
# broadcasting

x = np.array([10,8,16,40])
result = x**2
print(result)

# column er size and vector er size same hote hobe

mat = np.array([
    [10,20,30],
    [30,40,50],
])

result = mat +2
print(result)

vector = np.array([1,2,3])
result  = mat + vector
print(result)


[ 100   64  256 1600]
[[12 22 32]
 [32 42 52]]
[[11 22 33]
 [31 42 53]]


In [82]:
# logical function 
# comparison - >,<,>=,==,!=
x = np.array([10,8,30,40])
y = np.array([2,3,30,5])

greater_than = x>y
print(greater_than)
equal = x==y
print(equal)


# all () -> sob tru.e kina 
# any () -> jekono ekta true kina
print(np.all(greater_than))
print(np.any(equal))

[ True  True False  True]
[False False  True False]
False
True


In [84]:
# inplace sorting
x = np.array([10,8,30,40])
z = x.copy()


print(z)
z.sort()
print(z)


[10  8 30 40]
[ 8 10 30 40]


In [86]:
# copy sorting
print(x)
sort_arr = np.sort(x)
print(sort_arr)
print(x)

[10  8 30 40]
[ 8 10 30 40]
[10  8 30 40]


In [102]:
# 2d array sorting

# hrizon axis = 1
print(mat)
hor_sort = np.sort(mat,axis=1)
print(hor_sort)
var_sort = np.sort(mat,axis=0)
print(var_sort)

[[30  2 40]
 [ 4 20 50]]
[[ 2 30 40]
 [ 4 20 50]]
[[ 4  2 40]
 [30 20 50]]


In [109]:
# Searching 

x = np.array([10,8,30,40])
y = np.array([2,3,30,5])
print(x)
# np.where(condition,x,y) if true x, otherwise replace with y
index = np.where(x>8) # RETURNS INDEX
print(index)
index = np.where(x>8,x,0)  # RETURNS ARRAY
print(index)

[10  8 30 40]
(array([0, 2, 3]),)
[10  0 30 40]


In [115]:
print(mat)
index = np.where(mat>8) # returns index
print(index)

arr = np.where(mat>8,mat,0) # returns array
print(arr)

[[30  2 40]
 [ 4 20 50]]
(array([0, 0, 1, 1]), array([0, 2, 1, 2]))
[[30  0 40]
 [ 0 20 50]]


In [119]:
# maximum minimum
print(x)
maximum_value = np.argmax(x)
minimum_value = np.argmin(x)
print(maximum_value)
print(minimum_value)


[10  8 30 40]
3
1


In [124]:
# array counting
a = np.random.randint(1,100,size=(100,)) 
print(a)
value_grater_than_60 = np.count_nonzero(a<30)
print(value_grater_than_60)

[ 1 78  4 80 35 27 55 57 94 56  7 84 83 11 64 66 44 22 14 52 57 37 58 46
 31  3 64 81 14 76 97  3 86 19 38 41 98 58 68 48  4 62  3 47 21 52 83  1
 69  1 79  8 77 39 24 76 45 92 72 18 71 75 86 60 24 36 31 27 65 20 86 71
 46 40 12 65 62  6 22 46 50  7 89 74 14 16 20 42 26 97 25 91 58 45 47 72
 22 52 97 63]
32


In [129]:
unique_values,count = np.unique(a,return_counts=True)
print(unique_values,count)

[ 1  3  4  6  7  8 11 12 14 16 18 19 20 21 22 24 25 26 27 31 35 36 37 38
 39 40 41 42 44 45 46 47 48 50 52 55 56 57 58 60 62 63 64 65 66 68 69 71
 72 74 75 76 77 78 79 80 81 83 84 86 89 91 92 94 97 98] [3 3 2 1 2 1 1 1 3 1 1 1 2 1 3 2 1 1 2 2 1 1 1 1 1 1 1 1 1 2 3 2 1 1 3 1 1
 2 3 1 2 1 2 2 1 1 1 2 2 1 1 2 1 1 1 1 1 2 1 3 1 1 1 1 3 1]


In [140]:
# statical function
# data load
data = np.genfromtxt('student_scores.csv',delimiter=',',skip_header=1)
# print(data)
math_marks = data[::,:1]
print(math_marks.T)
max_math_marks = np.max(math_marks)
print(max_math_marks)
min_math_marks = np.min(math_marks)
print(min_math_marks)
avg_math_marks = np.mean(math_marks)
print(avg_math_marks)
median_math_marks = np.median(math_marks)
print(median_math_marks)


# Standard deviation
std_math_marks = np.std(math_marks)
print(std_math_marks)

[[78. 56. 89. 45. 70. 92. 61. 55. 88. 74. 66. 80. 59. 73. 91. 68. 77. 84.
  62. 95.]]
95.0
45.0
73.15
73.5
13.788672887555204


In [141]:
# correlation matrix:
study_hours = np.array([2,4,5,7,8])
exam_scores = np.array([65,75,78,88,92])
data = np.array([study_hours,exam_scores])
print(data)

[[ 2  4  5  7  8]
 [65 75 78 88 92]]


In [142]:
correlation = np.corrcoef(data)
print(correlation)


[[1.         0.99859154]
 [0.99859154 1.        ]]


In [147]:
# Liniar algebra
A = np.array([
    [1,2,3],
    [4,5,6],
])
B= np.array([
    [7,8],
    [9,10],
    [11,12],
])

# a er collumn and b er row same length hote hobe
dot_product = np.dot(A,B)
print(dot_product)
# trace
print(np.trace(B))






[[ 58  64]
 [139 154]]
17


In [151]:
# determinent

sq_mt = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print(sq_mt)
det_of_sq = np.linalg.det(sq_mt)
print(det_of_sq)
rank_sq = np.linalg.matrix_rank(sq_mt)
print(rank_sq)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
6.66133814775094e-16
2


In [ ]:
# https://www.deep-ml.com/problems/4

import numpy as np

def calculate_matrix_mean(matrix: list[list[float]], mode: str) -> list[float]:

	mat = np.array(matrix)
	if mode == 'row':
		means = np.mean(matrix,axis=1).tolist()
	else:
		means = np.mean(matrix,axis=0).tolist()
	return means
    

In [ ]:
# https://www.deep-ml.com/problems/1
import numpy as np
def matrix_dot_vector(a: list[list[int|float]], b: list[int|float]) -> list[int|float]:
	a = np.array(a)
    b = np.array(b)

    shape_a = a.shape
    if shape_a[1] != b.size:
        return -1
    dot = np.dot(a,b).tolist()
    return dot
	

In [6]:
import numpy as np
a = np.array([1,2,3,4,5,6])
b = a.reshape(2,3)
print(b.shape)
print(a)
print(np.sin(np.pi/2))
s = np.array([3,1,2])
print(np.sort(s))

x = np.array([
    [1,2],
    [3,4]
])
y = np.array([
    [5,6],
    [7,8]
])
ans = np.dot(x,y)
print(ans)

(2, 3)
[1 2 3 4 5 6]
1.0
[1 2 3]
[[19 22]
 [43 50]]


In [ ]:
# https://www.deep-ml.com/problems/2
import numpy as np

def transpose_matrix(a: list[list[int|float]]) -> list[list[int|float]]:

    a = np.array(a)
    b = np.transpose(a)
	return b